export const shoesSeed = [
  {
    name: "Burgundy Patent Bow Slingbacks",
    description: "Burgundy patent leather slingback heels with bow detail.",
    price: 360.0,
    quantity: 5,
    badge: "Best Seller",
    images: ["/products/5f31136f-e870-46a8-b50e-20ae25e1096e.jpeg"],
  },
  {
    name: "Chestnut Knot-Front Mules",
    description: "Chestnut brown knot-front mule heels.",
    price: 320.0,
    quantity: 5,
    badge: null,
    images: ["/products/a627bba2-e33c-46a4-90bb-05b05faafff8.jpeg"],
  },
  {
    name: "Rust Ruffle Trim Mules",
    description: "Rust orange mule heels with ruffle trim.",
    price: 340.0,
    quantity: 5,
    badge: "New",
    images: ["/products/9dd7dba2-78de-49bf-bf7a-29b7565ca67e.jpeg"],
  },
  {
    name: "Cognac Patent Pointed Pumps",
    description: "Cognac brown patent leather pointed pumps.",
    price: 330.0,
    quantity: 5,
    badge: null,
    images: ["/products/946b1cd7-e333-43cf-9053-f311e9725f90.jpeg"],
  },
  {
    name: "Cherry Red Bow Slingbacks",
    description: "Cherry red patent leather slingback heels with bow detail.",
    price: 360.0,
    quantity: 5,
    badge: null,
    images: ["/products/1cb054f1-e0d0-47f6-bb89-53fbaa4a2f38.jpeg"],
  },
  {
    name: "Gold Knot T-Strap Sandals",
    description: "Gold flat T-strap sandals with knot detail.",
    price: 220.0,
    quantity: 5,
    badge: null,
    images: ["/products/ebe20a69-9a81-49a8-9811-7bdf325d223c.jpeg"],
  },
  {
    name: "Blush Patent Bow Slingbacks",
    description: "Blush pink patent leather slingback pumps with bow detail.",
    price: 350.0,
    quantity: 5,
    badge: null,
    images: ["/products/85fe4429-82bf-4b00-addb-242585aaff6d.jpeg"],
  },
];
